In [1]:
import pandas as pd
import numpy as np

In [2]:
# Series
ds=pd.Series([10,20,30,40])
ds

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
# index change
ds=pd.Series([10,20,30,40],index=[1,2,3,4])
ds

1    10
2    20
3    30
4    40
dtype: int64

In [4]:
ds=pd.Series({"B":1,"H":2,"A":3})
ds

B    1
H    2
A    3
dtype: int64

In [5]:
ds=pd.Series(np.arange(75,100))
ds

0     75
1     76
2     77
3     78
4     79
5     80
6     81
7     82
8     83
9     84
10    85
11    86
12    87
13    88
14    89
15    90
16    91
17    92
18    93
19    94
20    95
21    96
22    97
23    98
24    99
dtype: int64

In [6]:
type(ds)

pandas.core.series.Series

In [7]:
# DataFrame
df=pd.DataFrame([["hey","jude","i"],["love","music","tune"]],index=["a","b"],columns=["p","q","r"])
df

      p      q     r
a   hey   jude     i
b  love  music  tune

In [8]:
df=pd.DataFrame({
    "p":[1,2,3,4],
    "q":[5,6,7,8]
})
df

   p  q
0  1  5
1  2  6
2  3  7
3  4  8

In [9]:
df=pd.DataFrame({
    "p":[1,2,3,4],
    "q":[5,6,7,8]
},columns=["x","y"])
df

Empty DataFrame
Columns: [x, y]
Index: []

In [10]:
df=pd.DataFrame(np.array([[1,2,3,4],[5,7,8,9]]))
df

   0  1  2  3
0  1  2  3  4
1  5  7  8  9

In [11]:
df=pd.DataFrame([
    {
         "p":[1,2,3,4],
        "q":[5,6,7,8]
    },
    {
       "a":["t","p","m","n"],
        "b":["l","g","b","t"]
    }
])
df

              p             q             a             b
0  [1, 2, 3, 4]  [5, 6, 7, 8]           NaN           NaN
1           NaN           NaN  [t, p, m, n]  [l, g, b, t]

In [12]:
df=pd.DataFrame([
    {
         "p":[1,2,3,4],
        "q":[5,6,7,8]
    },
    {
       "p":["t","p","m","n"],
        "q":["l","g","b","t"]
    }
])
df

              p             q
0  [1, 2, 3, 4]  [5, 6, 7, 8]
1  [t, p, m, n]  [l, g, b, t]

In [13]:
df=pd.read_csv("../Datasets/train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [14]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [15]:
df.shape

(891, 12)

In [16]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [17]:
df.size

10692

In [18]:
df.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], shape=(891, 12), dtype=object)

In [19]:
df.ndim

2

In [20]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [22]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [23]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,881,882,883,884,885,886,887,888,889,890
PassengerId,1,2,3,4,5,6,7,8,9,10,...,882,883,884,885,886,887,888,889,890,891
Survived,0,1,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,1,0,1,0
Pclass,3,1,3,1,3,3,1,3,3,2,...,3,3,2,3,3,2,1,3,1,3
Name,"Braund, Mr. Owen Harris","Cumings, Mrs. John Bradley (Florence Briggs Th...","Heikkinen, Miss. Laina","Futrelle, Mrs. Jacques Heath (Lily May Peel)","Allen, Mr. William Henry","Moran, Mr. James","McCarthy, Mr. Timothy J","Palsson, Master. Gosta Leonard","Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)","Nasser, Mrs. Nicholas (Adele Achem)",...,"Markun, Mr. Johann","Dahlberg, Miss. Gerda Ulrika","Banfield, Mr. Frederick James","Sutehall, Mr. Henry Jr","Rice, Mrs. William (Margaret Norton)","Montvila, Rev. Juozas","Graham, Miss. Margaret Edith","Johnston, Miss. Catherine Helen ""Carrie""","Behr, Mr. Karl Howell","Dooley, Mr. Patrick"
Sex,male,female,female,female,male,male,male,male,female,female,...,male,female,male,male,female,male,female,female,male,male
Age,22.0,38.0,26.0,35.0,35.0,NaN,54.0,2.0,27.0,14.0,...,33.0,22.0,28.0,25.0,39.0,27.0,19.0,NaN,26.0,32.0
SibSp,1,1,0,1,0,0,0,3,0,1,...,0,0,0,0,0,0,0,1,0,0
Parch,0,0,0,0,0,0,0,1,2,0,...,0,0,0,0,5,0,0,2,0,0
Ticket,A/5 21171,PC 17599,STON/O2. 3101282,113803,373450,330877,17463,349909,347742,237736,...,349257,7552,C.A./SOTON 34068,SOTON/OQ 392076,382652,211536,112053,W./C. 6607,111369,370376
Fare,7.25,71.2833,7.925,53.1,8.05,8.4583,51.8625,21.075,11.1333,30.0708,...,7.8958,10.5167,10.5,7.05,29.125,13.0,30.0,23.45,30.0,7.75
Cabin,NaN,C85,NaN,C123,NaN,NaN,E46,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,B42,NaN,C148,NaN
Embarked,S,C,S,S,S,Q,S,S,S,C,...,S,S,S,S,Q,S,S,S,C,Q

In [24]:
df["Pclass"]

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [25]:
type(df["Pclass"])

pandas.core.series.Series

In [26]:
df[["Pclass","Age"]]

     Pclass   Age
0         3  22.0
1         1  38.0
2         3  26.0
3         1  35.0
4         3  35.0
..      ...   ...
886       2  27.0
887       1  19.0
888       3   NaN
889       1  26.0
890       3  32.0

[891 rows x 2 columns]

In [27]:
df["Age"]>18

0       True
1       True
2       True
3       True
4       True
       ...
886     True
887     True
888    False
889     True
890     True
Name: Age, Length: 891, dtype: bool

In [28]:
df[df["Age"]>18]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [29]:
df[(df["Sex"]=="male") & (df["Age"]>18)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [30]:
malesurvived=df[(df["Sex"]=="male") & (df["Survived"]==1)]
femalesurvived=df[(df["Sex"]=="female") & (df["Survived"]==1)]
print("males=",malesurvived.shape[0])
print("females=",femalesurvived.shape[0])

males= 109
females= 233

In [31]:
df.iloc[2,2]

np.int64(3)

In [32]:
df.iloc[:,3]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [33]:
df.iloc[:10,3:9]

,Name,Sex,Age,SibSp,Parch,Ticket
0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599
2,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803
4,"Allen, Mr. William Henry",male,35.0,0,0,373450
5,"Moran, Mr. James",male,NaN,0,0,330877
6,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463
7,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909
8,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742
9,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736

In [34]:
df=pd.DataFrame({
    "sub":["Python","FSD","COA","TOC","DM"],
    "faculty":["VHA","PSP","VBY","DPS","MSS"],
    "marks":[10,9,10,9,9]
})
df

      sub faculty  marks
0  Python     VHA     10
1     FSD     PSP      9
2     COA     VBY     10
3     TOC     DPS      9
4      DM     MSS      9

In [35]:
df.set_index("sub",drop=False)

           sub faculty  marks
sub
Python  Python     VHA     10
FSD        FSD     PSP      9
COA        COA     VBY     10
TOC        TOC     DPS      9
DM          DM     MSS      9

In [36]:
df=df.set_index("sub",drop=True)
df

       faculty  marks
sub
Python     VHA     10
FSD        PSP      9
COA        VBY     10
TOC        DPS      9
DM         MSS      9

In [37]:
df=df.reset_index()
df

      sub faculty  marks
0  Python     VHA     10
1     FSD     PSP      9
2     COA     VBY     10
3     TOC     DPS      9
4      DM     MSS      9

In [38]:
df=pd.read_csv("../Datasets/train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [39]:
df=df.set_index("Name")
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [40]:
df.loc["Futrelle, Mrs. Jacques Heath (Lily May Peel)"]

PassengerId         4
Survived            1
Pclass              1
Sex            female
Age              35.0
SibSp               1
Parch               0
Ticket         113803
Fare             53.1
Cabin            C123
Embarked            S
Name: Futrelle, Mrs. Jacques Heath (Lily May Peel), dtype: object

In [41]:
df=pd.DataFrame({
    "sub":["Python","FSD","COA","TOC","DM"],
    "faculty":["VHA","PSP","VBY","DPS","MSS"],
    "marks":[10,9,10,9,9]
})
df

      sub faculty  marks
0  Python     VHA     10
1     FSD     PSP      9
2     COA     VBY     10
3     TOC     DPS      9
4      DM     MSS      9

In [42]:
df=df.set_index("sub")
df

       faculty  marks
sub
Python     VHA     10
FSD        PSP      9
COA        VBY     10
TOC        DPS      9
DM         MSS      9

In [43]:
df.loc["FSD","faculty"]

'PSP'

In [44]:
df.loc["FSD","faculty"]="NAS"
df

       faculty  marks
sub
Python     VHA     10
FSD        NAS      9
COA        VBY     10
TOC        DPS      9
DM         MSS      9

In [45]:
df.loc["FSD","marks"]=10
df

       faculty  marks
sub
Python     VHA     10
FSD        NAS     10
COA        VBY     10
TOC        DPS      9
DM         MSS      9

In [46]:
df.loc["project"]=["VHA",10]
df

        faculty  marks
sub
Python      VHA     10
FSD         NAS     10
COA         VBY     10
TOC         DPS      9
DM          MSS      9
project     VHA     10

In [47]:
df["HOD"]="MJT"
df

        faculty  marks  HOD
sub
Python      VHA     10  MJT
FSD         NAS     10  MJT
COA         VBY     10  MJT
TOC         DPS      9  MJT
DM          MSS      9  MJT
project     VHA     10  MJT

In [48]:
arr=np.random.rand(8,5)
arr

array([[0.79128915, 0.64925219, 0.08657457, 0.30614542, 0.34884698],
       [0.88279961, 0.49204953, 0.6898124 , 0.8615944 , 0.68508539],
       [0.09246447, 0.2518572 , 0.07782967, 0.60967328, 0.9998717 ],
       [0.64303657, 0.93160996, 0.12487918, 0.78993752, 0.75456756],
       [0.94172164, 0.27578149, 0.04772222, 0.3381852 , 0.62051389],
       [0.27692848, 0.57197063, 0.84878987, 0.59765646, 0.87354821],
       [0.4469011 , 0.11506841, 0.39986496, 0.21521305, 0.75230948],
       [0.74005883, 0.12642969, 0.65545441, 0.08850271, 0.90086598]])

In [49]:
df=pd.DataFrame(arr,columns=["A","B","C","D","E"])
df

          A         B         C         D         E
0  0.791289  0.649252  0.086575  0.306145  0.348847
1  0.882800  0.492050  0.689812  0.861594  0.685085
2  0.092464  0.251857  0.077830  0.609673  0.999872
3  0.643037  0.931610  0.124879  0.789938  0.754568
4  0.941722  0.275781  0.047722  0.338185  0.620514
5  0.276928  0.571971  0.848790  0.597656  0.873548
6  0.446901  0.115068  0.399865  0.215213  0.752309
7  0.740059  0.126430  0.655454  0.088503  0.900866

In [50]:
print("shape:",df.shape)
print("size:",df.size)
print("dim:",df.ndim)

shape: (8, 5)
size: 40
dim: 2

In [51]:
df["sum"]=df["A"]+df["B"]+df["C"]+df["D"]+df["E"]
df

          A         B         C         D         E       sum
0  0.791289  0.649252  0.086575  0.306145  0.348847  2.182108
1  0.882800  0.492050  0.689812  0.861594  0.685085  3.611341
2  0.092464  0.251857  0.077830  0.609673  0.999872  2.031696
3  0.643037  0.931610  0.124879  0.789938  0.754568  3.244031
4  0.941722  0.275781  0.047722  0.338185  0.620514  2.223924
5  0.276928  0.571971  0.848790  0.597656  0.873548  3.168894
6  0.446901  0.115068  0.399865  0.215213  0.752309  1.929357
7  0.740059  0.126430  0.655454  0.088503  0.900866  2.511312

In [52]:
df.iloc[5,2]=699
df

          A         B           C         D         E       sum
0  0.791289  0.649252    0.086575  0.306145  0.348847  2.182108
1  0.882800  0.492050    0.689812  0.861594  0.685085  3.611341
2  0.092464  0.251857    0.077830  0.609673  0.999872  2.031696
3  0.643037  0.931610    0.124879  0.789938  0.754568  3.244031
4  0.941722  0.275781    0.047722  0.338185  0.620514  2.223924
5  0.276928  0.571971  699.000000  0.597656  0.873548  3.168894
6  0.446901  0.115068    0.399865  0.215213  0.752309  1.929357
7  0.740059  0.126430    0.655454  0.088503  0.900866  2.511312

In [53]:
df.iloc[1:7,1:4]

          B           C         D
1  0.492050    0.689812  0.861594
2  0.251857    0.077830  0.609673
3  0.931610    0.124879  0.789938
4  0.275781    0.047722  0.338185
5  0.571971  699.000000  0.597656
6  0.115068    0.399865  0.215213

In [54]:
df.loc[7]=[1,2,3,4,5,90]
df

          A         B           C         D         E        sum
0  0.791289  0.649252    0.086575  0.306145  0.348847   2.182108
1  0.882800  0.492050    0.689812  0.861594  0.685085   3.611341
2  0.092464  0.251857    0.077830  0.609673  0.999872   2.031696
3  0.643037  0.931610    0.124879  0.789938  0.754568   3.244031
4  0.941722  0.275781    0.047722  0.338185  0.620514   2.223924
5  0.276928  0.571971  699.000000  0.597656  0.873548   3.168894
6  0.446901  0.115068    0.399865  0.215213  0.752309   1.929357
7  1.000000  2.000000    3.000000  4.000000  5.000000  90.000000

In [55]:
arr=np.random.rand(5,4)
df=pd.DataFrame(arr,columns=["CourseID","CourseName","Credits","Faculty"])
df

   CourseID  CourseName   Credits   Faculty
0  0.075789    0.725598  0.761213  0.052204
1  0.602857    0.268759  0.927136  0.512693
2  0.754660    0.765011  0.597874  0.793572
3  0.109852    0.506875  0.108753  0.268375
4  0.751578    0.329816  0.754753  0.376384

In [56]:
df.set_index("CourseID",inplace=True)
df

          CourseName   Credits   Faculty
CourseID
0.075789    0.725598  0.761213  0.052204
0.602857    0.268759  0.927136  0.512693
0.754660    0.765011  0.597874  0.793572
0.109852    0.506875  0.108753  0.268375
0.751578    0.329816  0.754753  0.376384

In [57]:
df["Semester"]=1
df

          CourseName   Credits   Faculty  Semester
CourseID
0.075789    0.725598  0.761213  0.052204         1
0.602857    0.268759  0.927136  0.512693         1
0.754660    0.765011  0.597874  0.793572         1
0.109852    0.506875  0.108753  0.268375         1
0.751578    0.329816  0.754753  0.376384         1

In [58]:
df.iloc[1,1]=44
df

          CourseName    Credits   Faculty  Semester
CourseID
0.075789    0.725598   0.761213  0.052204         1
0.602857    0.268759  44.000000  0.512693         1
0.754660    0.765011   0.597874  0.793572         1
0.109852    0.506875   0.108753  0.268375         1
0.751578    0.329816   0.754753  0.376384         1

In [59]:
df.loc[69]=[1,2,3,4]
df

           CourseName    Credits   Faculty  Semester
CourseID
0.075789     0.725598   0.761213  0.052204         1
0.602857     0.268759  44.000000  0.512693         1
0.754660     0.765011   0.597874  0.793572         1
0.109852     0.506875   0.108753  0.268375         1
0.751578     0.329816   0.754753  0.376384         1
69.000000    1.000000   2.000000  3.000000         4

In [60]:
train_df=pd.read_csv("../Datasets/train.csv")
train_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [61]:
train_df.head(8)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [62]:
train_df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [63]:
train_df.sample(9)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
159,160,0,3,"Sage, Master. Thomas Henry",male,NaN,8,2,CA. 2343,69.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
372,373,0,3,"Beavan, Mr. William Thomas",male,19.0,0,0,323951,8.0500,NaN,S
468,469,0,3,"Scanlan, Mr. James",male,NaN,0,0,36209,7.7250,NaN,Q
448,449,1,3,"Baclini, Miss. Marie Catherine",female,5.0,2,1,2666,19.2583,NaN,C
266,267,0,3,"Panula, Mr. Ernesti Arvid",male,16.0,4,1,3101295,39.6875,NaN,S
530,531,1,2,"Quick, Miss. Phyllis May",female,2.0,1,1,26360,26.0000,NaN,S
800,801,0,2,"Ponesell, Mr. Martin",male,34.0,0,0,250647,13.0000,NaN,S
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S

In [64]:
train_df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [65]:
train_df.describe(include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Dooley, Mr. Patrick",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [66]:
train_df.describe(include="object")

                       Name   Sex  Ticket Cabin Embarked
count                   891   891     891   204      889
unique                  891     2     681   147        3
top     Dooley, Mr. Patrick  male  347082    G6        S
freq                      1   577       7     4      644

In [67]:
train_df.describe(exclude="int")

,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
count,891,891,714.000000,891,891.000000,204,889
unique,891,2,NaN,681,NaN,147,3
top,"Dooley, Mr. Patrick",male,NaN,347082,NaN,G6,S
freq,1,577,NaN,7,NaN,4,644
mean,NaN,NaN,29.699118,NaN,32.204208,NaN,NaN
std,NaN,NaN,14.526497,NaN,49.693429,NaN,NaN
min,NaN,NaN,0.420000,NaN,0.000000,NaN,NaN
25%,NaN,NaN,20.125000,NaN,7.910400,NaN,NaN
50%,NaN,NaN,28.000000,NaN,14.454200,NaN,NaN
75%,NaN,NaN,38.000000,NaN,31.000000,NaN,NaN
max,NaN,NaN,80.000000,NaN,512.329200,NaN,NaN

In [68]:
df=pd.DataFrame([[1,np.nan,3,4],[2,4,np.nan,8],[np.nan,4,5,9],[np.nan,1,np.nan,3],[np.nan,np.nan,np.nan,9],[1,1,1,1]],columns=["A","B","C","D"])
df

     A    B    C  D
0  1.0  NaN  3.0  4
1  2.0  4.0  NaN  8
2  NaN  4.0  5.0  9
3  NaN  1.0  NaN  3
4  NaN  NaN  NaN  9
5  1.0  1.0  1.0  1

In [69]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False   True  False
2   True  False  False  False
3   True  False   True  False
4   True   True   True  False
5  False  False  False  False

In [70]:
df.isna().sum()

A    3
B    2
C    3
D    0
dtype: int64

In [71]:
train_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [72]:
df.dropna(axis=0)#by default how="any"

     A    B    C  D
5  1.0  1.0  1.0  1

In [73]:
df.dropna(axis=1)

   D
0  4
1  8
2  9
3  3
4  9
5  1

In [74]:
df.dropna(how="all")#will drop a row that contains all NaN

     A    B    C  D
0  1.0  NaN  3.0  4
1  2.0  4.0  NaN  8
2  NaN  4.0  5.0  9
3  NaN  1.0  NaN  3
4  NaN  NaN  NaN  9
5  1.0  1.0  1.0  1

In [75]:
df.dropna(subset=["A"])

     A    B    C  D
0  1.0  NaN  3.0  4
1  2.0  4.0  NaN  8
5  1.0  1.0  1.0  1

In [76]:
df.dropna(subset=["B","C"])#will drop any row that contains NaN in B and C column

     A    B    C  D
2  NaN  4.0  5.0  9
5  1.0  1.0  1.0  1

In [77]:
df.dropna(subset=["B","C"],how="all")#will drop rows that contains NaN in both B and C together

     A    B    C  D
0  1.0  NaN  3.0  4
1  2.0  4.0  NaN  8
2  NaN  4.0  5.0  9
3  NaN  1.0  NaN  3
5  1.0  1.0  1.0  1

In [78]:
df.dropna(thresh=3)#a row must have more than three non NaN values

     A    B    C  D
0  1.0  NaN  3.0  4
1  2.0  4.0  NaN  8
2  NaN  4.0  5.0  9
5  1.0  1.0  1.0  1

In [79]:
train_df.dropna(subset=["Cabin"])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [80]:
df["A"]=df["A"].fillna(df["A"].mean())

In [81]:
df

          A    B    C  D
0  1.000000  NaN  3.0  4
1  2.000000  4.0  NaN  8
2  1.333333  4.0  5.0  9
3  1.333333  1.0  NaN  3
4  1.333333  NaN  NaN  9
5  1.000000  1.0  1.0  1

In [82]:
train_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [83]:
train_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [84]:
train_df["Age"]=train_df["Age"].fillna(train_df.Age.mean())

In [85]:
train_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [86]:
train_df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             89
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [87]:
train_df.Sex.unique()

array(['male', 'female'], dtype=object)

In [88]:
train_df.Sex.value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [89]:
train_df.Embarked.value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [90]:
train_df["Embarked"]=train_df["Embarked"].fillna(train_df.Embarked.mode()[0])

In [91]:
train_df.Embarked.value_counts()

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

### Concat

In [92]:
df1=pd.DataFrame({
    "A":[1,2],
    "B":[3,4]
})
df1

   A  B
0  1  3
1  2  4

In [93]:
df2=pd.DataFrame({
    "A":[5,6],
    "B":[7,8]
})
df2

   A  B
0  5  7
1  6  8

In [94]:
pd.concat((df1,df2),axis=0)

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [95]:
pd.concat([df1,df2],axis=0,ignore_index=True)

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

In [96]:
pd.concat([df1,df2],axis=0,keys=["df1","df2"])

       A  B
df1 0  1  3
    1  2  4
df2 0  5  7
    1  6  8

In [97]:
pd.concat([df1,df2],axis=1)

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [98]:
df3=pd.DataFrame({
    "C":[5,6],
    "B":[7,8]
})
df3

   C  B
0  5  7
1  6  8

In [99]:
pd.concat([df1,df3],axis=0)

     A  B    C
0  1.0  3  NaN
1  2.0  4  NaN
0  NaN  7  5.0
1  NaN  8  6.0

In [100]:
pd.concat((df1,df3),axis=1)

   A  B  C  B
0  1  3  5  7
1  2  4  6  8

In [101]:
pd.concat((df1,df3),axis=1,sort=True)

   A  B  C  B
0  1  3  5  7
1  2  4  6  8

In [102]:
df4=pd.DataFrame({
    "A":[1,2,3],
    "B":[3,4,5]
})
df4

   A  B
0  1  3
1  2  4
2  3  5

In [103]:
pd.concat([df4,df3],axis=1)

   A  B    C    B
0  1  3  5.0  7.0
1  2  4  6.0  8.0
2  3  5  NaN  NaN

In [104]:
pd.concat((df4,df3))

     A  B    C
0  1.0  3  NaN
1  2.0  4  NaN
2  3.0  5  NaN
0  NaN  7  5.0
1  NaN  8  6.0

In [105]:
pd.concat((df4,df3),join="inner")

   B
0  3
1  4
2  5
0  7
1  8

In [106]:
pd.concat((df4,df3),join="outer")

     A  B    C
0  1.0  3  NaN
1  2.0  4  NaN
2  3.0  5  NaN
0  NaN  7  5.0
1  NaN  8  6.0

### Sort

In [107]:
df1=pd.DataFrame({"D":[1,2],"B":[3,4]})
df2=pd.DataFrame({"C":[5,6],"A":[7,8]})

In [108]:
pd.concat([df1,df2],sort=True)

     A    B    C    D
0  NaN  3.0  NaN  1.0
1  NaN  4.0  NaN  2.0
0  7.0  NaN  5.0  NaN
1  8.0  NaN  6.0  NaN

In [109]:
pd.concat([df1,df2],sort=False)

     D    B    C    A
0  1.0  3.0  NaN  NaN
1  2.0  4.0  NaN  NaN
0  NaN  NaN  5.0  7.0
1  NaN  NaN  6.0  8.0

### Merge

In [110]:
df1=pd.DataFrame({
    "name":["VHA","PSP","VBY","DPS","MSS"],
    "sub":["python","fsd","coa","toc","dm"],
    "id":[3,2,1,6,4]
})
df1

  name     sub  id
0  VHA  python   3
1  PSP     fsd   2
2  VBY     coa   1
3  DPS     toc   6
4  MSS      dm   4

In [111]:
df2=pd.DataFrame({
    "id":[1,2,3,4,5],
    "marks":[10,9,10,9,9]
})
df2

   id  marks
0   1     10
1   2      9
2   3     10
3   4      9
4   5      9

In [112]:
pd.merge(df1,df2,on="id")

  name     sub  id  marks
0  VHA  python   3     10
1  PSP     fsd   2      9
2  VBY     coa   1     10
3  MSS      dm   4      9

In [113]:
pd.merge(df1,df2,on="id",how="inner")

  name     sub  id  marks
0  VHA  python   3     10
1  PSP     fsd   2      9
2  VBY     coa   1     10
3  MSS      dm   4      9

In [114]:
pd.merge(df1,df2,on="id",how="outer")

  name     sub  id  marks
0  VBY     coa   1   10.0
1  PSP     fsd   2    9.0
2  VHA  python   3   10.0
3  MSS      dm   4    9.0
4  NaN     NaN   5    9.0
5  DPS     toc   6    NaN

In [115]:
pd.merge(df1,df2,on="id",how="left")

  name     sub  id  marks
0  VHA  python   3   10.0
1  PSP     fsd   2    9.0
2  VBY     coa   1   10.0
3  DPS     toc   6    NaN
4  MSS      dm   4    9.0

In [116]:
pd.merge(df1,df2,on="id",how="right")

  name     sub  id  marks
0  VBY     coa   1     10
1  PSP     fsd   2      9
2  VHA  python   3     10
3  MSS      dm   4      9
4  NaN     NaN   5      9

In [117]:
pd.merge(df1,df2,how="cross")

   name     sub  id_x  id_y  marks
0   VHA  python     3     1     10
1   VHA  python     3     2      9
2   VHA  python     3     3     10
3   VHA  python     3     4      9
4   VHA  python     3     5      9
5   PSP     fsd     2     1     10
6   PSP     fsd     2     2      9
7   PSP     fsd     2     3     10
8   PSP     fsd     2     4      9
9   PSP     fsd     2     5      9
10  VBY     coa     1     1     10
11  VBY     coa     1     2      9
12  VBY     coa     1     3     10
13  VBY     coa     1     4      9
14  VBY     coa     1     5      9
15  DPS     toc     6     1     10
16  DPS     toc     6     2      9
17  DPS     toc     6     3     10
18  DPS     toc     6     4      9
19  DPS     toc     6     5      9
20  MSS      dm     4     1     10
21  MSS      dm     4     2      9
22  MSS      dm     4     3     10
23  MSS      dm     4     4      9
24  MSS      dm     4     5      9

In [118]:
pd.merge(df1,df2,left_index=True,right_index=True)

  name     sub  id_x  id_y  marks
0  VHA  python     3     1     10
1  PSP     fsd     2     2      9
2  VBY     coa     1     3     10
3  DPS     toc     6     4      9
4  MSS      dm     4     5      9

In [119]:
df1=pd.DataFrame({
    "name":["VHA","PSP","VBY","DPS","MSS"],
    "sub":["python","fsd","coa","toc","dm"],
    "in":[3,2,1,6,4]
})
df1

  name     sub  in
0  VHA  python   3
1  PSP     fsd   2
2  VBY     coa   1
3  DPS     toc   6
4  MSS      dm   4

In [120]:
df2=pd.DataFrame({
    "id":[1,2,3,4,5],
    "marks":[10,9,10,9,9]
    ,"fac":["VHA","NAS","VBY","DPS","MSS"]
})
df2

   id  marks  fac
0   1     10  VHA
1   2      9  NAS
2   3     10  VBY
3   4      9  DPS
4   5      9  MSS

In [121]:
df1.merge(df2,left_on="in",right_on="id")

  name     sub  in  id  marks  fac
0  VHA  python   3   3     10  VBY
1  PSP     fsd   2   2      9  NAS
2  VBY     coa   1   1     10  VHA
3  MSS      dm   4   4      9  DPS

In [122]:
df1.merge(df2,left_on="name",right_on="fac",how="outer")

  name     sub   in   id  marks  fac
0  DPS     toc  6.0  4.0    9.0  DPS
1  MSS      dm  4.0  5.0    9.0  MSS
2  NaN     NaN  NaN  2.0    9.0  NAS
3  PSP     fsd  2.0  NaN    NaN  NaN
4  VBY     coa  1.0  3.0   10.0  VBY
5  VHA  python  3.0  1.0   10.0  VHA

### Train Test Split

In [124]:
df=pd.read_csv("../Datasets/production_analysis_dataset.csv")
df

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045
5,106,Electronics,Plant_B,Morning,S2,621,28,8.23,1.12,846,20834
6,107,Furniture,Plant_B,Morning,S3,351,29,7.33,1.03,1173,12664
7,108,Electronics,Plant_B,Evening,S3,659,9,8.33,0.42,1546,14010
8,109,Electronics,Plant_A,Morning,S3,627,40,7.16,0.62,1586,22713
9,110,Automotive,Plant_B,Morning,S4,505,22,6.70,1.39,1380,24358
10,111,Automotive,Plant_B,Night,S4,502,34,6.93,0.38,1562,19197
11,112,Furniture,Plant_A,Morning,S1,598,30,7.59,1.50,941,18348
12,113,Furniture,Plant_C,Evening,S3,378,15,8.88,0.75,865,16304
13,114,Furniture,Plant_C,Evening,S1,583,5,8.54,0.35,1349,22302
14,115,Automotive,Plant_B,Night,S2,450,32,6.97,0.20,1539,24349
15,116,Automotive,Plant_A,Morning,S3,559,11,9.11,0.59,1454,18317
16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009
17,118,Electronics,Plant_A,Night,S1,357,28,9.14,1.28,1114,13923
18,119,Electronics,Plant_A,Night,S4,343,36,8.95,1.47,1345,22547
19,120,Automotive,Plant_C,Night,S2,581,15,7.30,1.33,1233,13470
20,121,Automotive,Plant_B,Morning,S2,665,24,7.70,1.07,1182,17177
21,122,Electronics,Plant_A,Morning,S1,415,9,7.51,0.96,1035,19641
22,123,Electronics,Plant_B,Night,S4,417,9,9.22,1.32,872,18423
23,124,Furniture,Plant_A,Evening,S4,409,39,6.90,1.42,1384,19440
24,125,Furniture,Plant_C,Morning,S1,397,11,6.79,0.76,1233,16735
25,126,Electronics,Plant_A,Night,S4,331,30,8.68,1.24,911,14073
26,127,Automotive,Plant_A,Morning,S1,371,32,7.05,0.80,877,17260
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166
28,129,Furniture,Plant_C,Night,S4,301,29,7.30,1.22,1265,14673
29,130,Automotive,Plant_A,Night,S3,379,17,7.39,1.46,1393,22054
30,131,Electronics,Plant_C,Morning,S2,329,8,8.25,0.85,1343,12579
31,132,Automotive,Plant_A,Night,S1,335,9,8.53,0.51,922,24586
32,133,Furniture,Plant_A,Night,S3,617,10,7.76,0.96,1335,15183
33,134,Furniture,Plant_A,Morning,S4,422,21,7.69,1.07,1107,17491
34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170
35,136,Automotive,Plant_C,Morning,S3,445,15,7.81,0.91,1109,20021
36,137,Electronics,Plant_C,Night,S2,639,11,9.32,0.37,918,24577
37,138,Automotive,Plant_B,Night,S4,439,23,8.31,1.13,1008,21263
38,139,Electronics,Plant_B,Morning,S3,428,8,6.78,0.75,1083,10722
39,140,Electronics,Plant_C,Morning,S1,382,33,8.16,0.76,809,11832
40,141,Electronics,Plant_B,Morning,S2,489,40,6.94,0.37,1115,15974
41,142,Automotive,Plant_A,Morning,S2,641,11,7.56,0.93,1216,20168
42,143,Furniture,Plant_C,Night,S2,390,31,6.57,1.16,1140,22818
43,144,Furniture,Plant_A,Morning,S4,436,15,8.86,0.34,839,24067
44,145,Automotive,Plant_A,Evening,S3,479,24,8.96,1.33,1028,10387
45,146,Furniture,Plant_C,Night,S3,442,9,9.40,0.56,1456,18346
46,147,Electronics,Plant_A,Night,S4,314,12,9.13,0.54,1394,14349
47,148,Automotive,Plant_A,Evening,S1,476,25,7.81,1.48,918,16311
48,149,Automotive,Plant_C,Night,S2,662,32,6.51,1.40,1351,21253
49,150,Furniture,Plant_C,Morning,S3,486,32,6.71,1.06,1138,20209

In [125]:
from sklearn.model_selection import train_test_split

In [130]:
df.columns

Index(['production_id', 'product_category', 'factory', 'shift', 'supervisor',
       'units_produced', 'defective_units', 'production_time_hr',
       'machine_downtime_hr', 'energy_consumption_kwh', 'profit'],
      dtype='object')

In [131]:
x=df[['production_id', 'product_category', 'factory', 'shift', 'supervisor',
       'units_produced', 'defective_units', 'production_time_hr',
       'machine_downtime_hr', 'energy_consumption_kwh']]
y=df["profit"]

In [134]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [137]:
print(x_train.shape)
print(x_test.shape)

(40, 10)
(10, 10)