### RandomForest

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report
import plotly.express as px

In [2]:
df=pd.read_csv("../Datasets/diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [3]:
x=df.drop("Outcome",axis=1)
y=df["Outcome"]

In [4]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [5]:
rf=RandomForestClassifier(n_estimators=51,criterion="entropy",random_state=42)
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
print("Accuracy:",accuracy_score(y_test,y_pred))
print("classfication report:",classification_report(y_test,y_pred))

Accuracy: 0.7662337662337663
classfication report:               precision    recall  f1-score   support

           0       0.82      0.82      0.82        99
           1       0.67      0.67      0.67        55

    accuracy                           0.77       154
   macro avg       0.75      0.75      0.75       154
weighted avg       0.77      0.77      0.77       154

In [6]:
acc=[]
for i in range(1,51):
    rf=RandomForestClassifier(n_estimators=i,criterion="entropy",random_state=42)
    rf.fit(x_train,y_train)
    y_pred=rf.predict(x_test)
    print("value of i:",i,"Accuracy:",accuracy_score(y_test,y_pred))
    acc.append(accuracy_score(y_test,y_pred))

value of i: 1 Accuracy: 0.6883116883116883
value of i: 2 Accuracy: 0.7012987012987013
value of i: 3 Accuracy: 0.7142857142857143
value of i: 4 Accuracy: 0.7272727272727273
value of i: 5 Accuracy: 0.7337662337662337
value of i: 6 Accuracy: 0.7597402597402597
value of i: 7 Accuracy: 0.7337662337662337
value of i: 8 Accuracy: 0.7207792207792207
value of i: 9 Accuracy: 0.7337662337662337
value of i: 10 Accuracy: 0.7402597402597403
value of i: 11 Accuracy: 0.7467532467532467
value of i: 12 Accuracy: 0.7467532467532467
value of i: 13 Accuracy: 0.7792207792207793
value of i: 14 Accuracy: 0.7532467532467533
value of i: 15 Accuracy: 0.7597402597402597
value of i: 16 Accuracy: 0.7662337662337663
value of i: 17 Accuracy: 0.7532467532467533
value of i: 18 Accuracy: 0.7662337662337663
value of i: 19 Accuracy: 0.7597402597402597
value of i: 20 Accuracy: 0.7597402597402597
value of i: 21 Accuracy: 0.7727272727272727
value of i: 22 Accuracy: 0.7792207792207793
value of i: 23 Accuracy: 0.7792207792207793
value of i: 24 Accuracy: 0.7727272727272727
value of i: 25 Accuracy: 0.7857142857142857
value of i: 26 Accuracy: 0.7792207792207793
value of i: 27 Accuracy: 0.7792207792207793
value of i: 28 Accuracy: 0.7792207792207793
value of i: 29 Accuracy: 0.7792207792207793
value of i: 30 Accuracy: 0.7597402597402597
value of i: 31 Accuracy: 0.7662337662337663
value of i: 32 Accuracy: 0.7597402597402597
value of i: 33 Accuracy: 0.7662337662337663
value of i: 34 Accuracy: 0.7597402597402597
value of i: 35 Accuracy: 0.7597402597402597
value of i: 36 Accuracy: 0.7597402597402597
value of i: 37 Accuracy: 0.7662337662337663
value of i: 38 Accuracy: 0.7597402597402597
value of i: 39 Accuracy: 0.7597402597402597
value of i: 40 Accuracy: 0.7662337662337663
value of i: 41 Accuracy: 0.7662337662337663
value of i: 42 Accuracy: 0.7597402597402597
value of i: 43 Accuracy: 0.7662337662337663
value of i: 44 Accuracy: 0.7662337662337663
value of i: 45 Accuracy: 0.7662337662337663
value of i: 46 Accuracy: 0.7727272727272727
value of i: 47 Accuracy: 0.7662337662337663
value of i: 48 Accuracy: 0.7662337662337663
value of i: 49 Accuracy: 0.7597402597402597
value of i: 50 Accuracy: 0.7662337662337663

In [7]:
px.line(x=range(1,51),y=acc)

In [8]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import GridSearchCV

In [9]:
cancer=load_breast_cancer()
x,y=cancer.data,cancer.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [10]:
param_grid={"n_estimators":[100,200,300],
            "max_depth":[None,5,10,20],
            "max_features":["sqrt","log2",None],
            "max_samples":[None,0.6,0.8]
            }
grid=GridSearchCV(estimator=RandomForestClassifier(random_state=42),param_grid=param_grid,n_jobs=-1,verbose=2,scoring="accuracy",cv=5)
grid.fit(x_train,y_train)
y_pred=grid.predict(x_test)
print(accuracy_score(y_test,y_pred))

Fitting 5 folds for each of 108 candidates, totalling 540 fits
0.9649122807017544

In [11]:
diabetes_df=pd.read_csv("../Datasets/diabetes.csv")
diabetes_df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [12]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

In [13]:
x=diabetes_df.drop("Outcome",axis=1)
y=diabetes_df["Outcome"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [14]:
svm=SVC(C=1)
svm.fit(x_train,y_train)
y_pred=svm.predict(x_test)
print(classification_report(y_pred,y_test))
print(accuracy_score(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.88      0.78      0.83       111
           1       0.56      0.72      0.63        43

    accuracy                           0.77       154
   macro avg       0.72      0.75      0.73       154
weighted avg       0.79      0.77      0.77       154

0.7662337662337663

In [15]:
for i in range(1,51):
    svm=SVC(C=i)
    svm.fit(x_train,y_train)
    y_pred=svm.predict(x_test)
    print(i,":",accuracy_score(y_pred,y_test))

1 : 0.7662337662337663
2 : 0.7727272727272727
3 : 0.7727272727272727
4 : 0.7597402597402597
5 : 0.7662337662337663
6 : 0.7597402597402597
7 : 0.7662337662337663
8 : 0.7662337662337663
9 : 0.7662337662337663
10 : 0.7662337662337663
11 : 0.7597402597402597
12 : 0.7662337662337663
13 : 0.7662337662337663
14 : 0.7727272727272727
15 : 0.7727272727272727
16 : 0.7727272727272727
17 : 0.7597402597402597
18 : 0.7532467532467533
19 : 0.7532467532467533
20 : 0.7597402597402597
21 : 0.7662337662337663
22 : 0.7597402597402597
23 : 0.7597402597402597
24 : 0.7597402597402597
25 : 0.7532467532467533
26 : 0.7467532467532467
27 : 0.7467532467532467
28 : 0.7467532467532467
29 : 0.7467532467532467
30 : 0.7467532467532467
31 : 0.7467532467532467
32 : 0.7467532467532467
33 : 0.7402597402597403
34 : 0.7402597402597403
35 : 0.7402597402597403
36 : 0.7402597402597403
37 : 0.7402597402597403
38 : 0.7402597402597403
39 : 0.7402597402597403
40 : 0.7337662337662337
41 : 0.7337662337662337
42 : 0.7337662337662337
43 : 0.7337662337662337
44 : 0.7337662337662337
45 : 0.7337662337662337
46 : 0.7337662337662337
47 : 0.7337662337662337
48 : 0.7337662337662337
49 : 0.7337662337662337
50 : 0.7402597402597403